In [66]:
#Importing the Neccessary Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

# Read the board_games.csv dataset
data = pd.read_csv("C:\\Users\\n\\Downloads\\board_games (1).csv")
data.head(5)

,game_id,name,max_players,playtime,min_age,min_players,age_of_game,users_rated,rating,CardGame,...,WorldWarII,Bluffing,Humor,Animals,Adventure,Medieval,Action.Dexterity,Deduction,Movies.TV.Radiotheme,Miniatures
0,1,Die Macher,5,240,14,3,36,4498,7.66508,No,...,No,No,No,No,No,No,No,No,No,No
1,2,Dragonmaster,4,30,12,3,41,478,6.60815,Yes,...,No,No,No,No,No,No,No,No,No,No
2,3,Samurai,4,60,10,2,24,12019,7.44119,No,...,No,No,No,No,No,Yes,No,No,No,No
3,4,Tal der Könige,4,60,12,2,30,314,6.60675,No,...,No,No,No,No,No,No,No,No,No,No
4,5,Acquire,6,90,12,3,58,15195,7.35830,No,...,No,No,No,No,No,No,No,No,No,No

In [73]:
data.tail(10)

,game_id,name,max_players,playtime,min_age,min_players,age_of_game,users_rated,rating,CardGame,...,WorldWarII,Bluffing,Humor,Animals,Adventure,Medieval,Action.Dexterity,Deduction,Movies.TV.Radiotheme,Miniatures
10428,211047,Steal This Game,2,5,14,2,6,50,6.92760,No,...,No,Yes,No,No,No,No,No,Yes,No,No
10429,211450,Take That,4,0,8,2,6,52,6.34615,Yes,...,No,No,No,No,No,No,No,No,No,No
10430,212445,Blood Bowl (2016 edition),2,120,12,2,6,632,8.39254,No,...,No,No,No,No,No,No,No,No,No,Yes
10431,212551,Qwixx: Das Duell,2,15,12,2,6,68,6.73088,No,...,No,No,No,No,No,No,No,No,No,No
10432,212956,Room 25 Ultimate,8,60,10,1,6,93,7.52656,No,...,No,Yes,No,No,No,No,No,No,Yes,No
10433,214996,"Silver Bayonet: The First Team in Vietnam, 196...",2,480,12,1,6,75,8.35333,No,...,No,No,No,No,No,No,No,No,No,No
10434,215437,Codex: Card-Time Strategy – Core Set,5,45,13,2,6,82,8.08780,Yes,...,No,No,No,No,No,No,No,No,No,No
10435,215471,Wind the Film!,4,20,12,2,6,63,7.28016,Yes,...,No,No,No,No,No,No,No,No,No,No
10436,216201,Robo Rally (2016),6,120,12,2,6,341,7.45871,No,...,No,No,No,No,No,No,No,No,No,Yes
10437,216725,Villages of Valeria: Deluxe Kickstarter Edition,5,60,14,1,6,119,7.52941,Yes,...,No,No,No,No,No,No,No,No,No,No

In [75]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10438 entries, 0 to 10437
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   game_id               10438 non-null  int64
 1   name                  10438 non-null  object
 2   max_players           10438 non-null  int64
 3   playtime              10438 non-null  int64
 4   min_age               10438 non-null  int64
 5   min_players           10438 non-null  int64
 6   age_of_game           10438 non-null  int64
 7   users_rated           10438 non-null  int64
 8   rating                10438 non-null  float64
 9   CardGame              10438 non-null  object
 10  Wargame               10438 non-null  object
 11  Fantasy               10438 non-null  object
 12  Fighting              10438 non-null  object
 13  Economic              10438 non-null  object
 14  Science.Fiction       10438 non-null  object
 15  Dice                  10438 non-null  object
 16  Party.Game            10438 non-null  object
 17  AbstractStrategy      10438 non-null  object
 18  Childrens.Game        10438 non-null  object
 19  WorldWarII            10438 non-null  object
 20  Bluffing              10438 non-null  object
 21  Humor                 10438 non-null  object
 22  Animals               10438 non-null  object
 23  Adventure             10438 non-null  object
 24  Medieval              10438 non-null  object
 25  Action.Dexterity      10438 non-null  object
 26  Deduction             10438 non-null  object
 27  Movies.TV.Radiotheme  10438 non-null  object
 28  Miniatures            10438 non-null  object
dtypes: float64(1), int64(7), object(21)
memory usage: 2.3+ MB

In [78]:
data.describe()

,game_id,max_players,playtime,min_age,min_players,age_of_game,users_rated,rating
count,10438.000000,10438.000000,10438.000000,10438.000000,10438.000000,10438.000000,10438.000000,10438.000000
mean,61708.387526,5.639299,91.754934,9.718049,2.069554,18.965032,874.832727,6.372833
std,65987.382303,18.904446,662.697815,3.457391,0.665288,12.283071,2892.064444,0.850985
min,1.000000,0.000000,0.000000,0.000000,0.000000,6.000000,50.000000,1.384210
25%,5439.500000,4.000000,30.000000,8.000000,2.000000,10.000000,85.000000,5.831313
50%,28544.500000,4.000000,45.000000,10.000000,2.000000,15.000000,176.000000,6.394940
75%,125815.250000,6.000000,90.000000,12.000000,2.000000,24.000000,519.750000,6.945292
max,216725.000000,999.000000,60000.000000,42.000000,9.000000,72.000000,67655.000000,9.003920

In [82]:
data.isnull()

,game_id,name,max_players,playtime,min_age,min_players,age_of_game,users_rated,rating,CardGame,...,WorldWarII,Bluffing,Humor,Animals,Adventure,Medieval,Action.Dexterity,Deduction,Movies.TV.Radiotheme,Miniatures
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [90]:
#Question 1
from sklearn.preprocessing import LabelEncoder

# Encode categorical variables
X_encoded = X.copy()
for column in X_encoded.columns:
    if X_encoded[column].dtype == object:
        X_encoded[column] = LabelEncoder().fit_transform(X_encoded[column])

# Question 1
X_all = X_encoded[predictors]
tree_all = DecisionTreeRegressor(random_state=0)
tree_all.fit(X_all, y)
# Calculate RMSE of tree_all
y_pred_all = tree_all.predict(X_all)
rmse_all = mean_squared_error(y, y_pred_all, squared=False)
print("The RMSE for all predictors are:",rmse_all)

The RMSE for all predictors are: 0.13077793373406543

In [91]:
# Question 2
tree6 = DecisionTreeRegressor(random_state=0, ccp_alpha=0.005)
tree6.fit(X_all, y)
num_leaves_tree6 = tree6.get_n_leaves()
print("The Number of leaves is:",num_leaves_tree6)

The Number of leaves is: 9

In [93]:
# Question 3
y_pred_tree6 = tree6.predict(X_all)
rmse_tree6 = mean_squared_error(y, y_pred_tree6, squared=False)
print("The RMSE of tree6 is:",rmse_tree6)

The RMSE of tree6 is: 0.7164482647979833

In [94]:
# Question 4
import numpy as np
cp_values = [0.001, 0.0001, 0.1]
trees = []
rmses = []
for cp in cp_values:
    tree = DecisionTreeRegressor(random_state=0, ccp_alpha=cp)
    tree.fit(X_all, y)
    trees.append(tree)
    y_pred = tree.predict(X_all)
    rmse = mean_squared_error(y, y_pred, squared=False)
    rmses.append(rmse)

min_rmse_idx = np.argmin(rmses)
best_tree = trees[min_rmse_idx]
best_tree_rmse = rmses[min_rmse_idx]
print("Tree with the lowest RMSE is:",best_tree_rmse)

Tree with the lowest RMSE is: 0.4443180581170673

In [86]:
#Number 5
import pandas as pd
from sklearn.model_selection import train_test_split

# Load the board_games dataset
board_games_data = data

# Separate the features (X) and the target variable (y)
X = board_games_data.drop(columns=["rating"])
y = board_games_data["rating"]

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print( X_test)

       game_id                     name  max_players  playtime  min_age  \
8005    130229             Out of Gears            8        30        8
9496    171630  Drakon (fourth edition)            6        40       10
7428    107464                   Kabuki            6        20        6
8728    150312   Welcome to the Dungeon            4        30       10
9519    172062          Fairytale Gloom            5        60       13
...        ...                      ...          ...       ...      ...
10324   202737             Box of Rocks           38        15       12
7337    102940              Trophy Buck            8        20        8
6637     67185                    Sobek            4        40        8
2275      4292  The Sword and the Flame            0        60       12
7438    107971        QI the Board Game            6         0        8

       min_players  age_of_game  users_rated CardGame Wargame  ... WorldWarII  \
8005             2           10          128       No      No  ...         No
9496             2            7          408       No      No  ...         No
7428             2           11          149       No      No  ...         No
8728             2            9         5624      Yes      No  ...         No
9519             2            7          274      Yes      No  ...         No
...            ...          ...          ...      ...     ...  ...        ...
10324            2            6           72       No      No  ...         No
7337             3           11          205       No      No  ...         No
6637             2           12         1657      Yes      No  ...         No
2275             0           43           91       No     Yes  ...         No
7438             2           11           59       No      No  ...         No

      Bluffing Humor Animals Adventure Medieval Action.Dexterity Deduction  \
8005       Yes    No      No        No       No               No       Yes
9496        No    No      No        No       No               No        No
7428        No    No      No        No       No               No        No
8728       Yes    No      No        No       No               No        No
9519        No   Yes      No        No       No               No        No
...        ...   ...     ...       ...      ...              ...       ...
10324       No   Yes      No        No       No               No        No
7337        No    No      No        No       No               No        No
6637        No    No      No        No       No               No        No
2275        No    No      No        No       No               No        No
7438        No    No      No        No       No               No        No

      Movies.TV.Radiotheme Miniatures
8005                    No         No
9496                    No        Yes
7428                    No         No
8728                    No         No
9519                    No         No
...                    ...        ...
10324                   No         No
7337                    No         No
6637                    No         No
2275                    No        Yes
7438                   Yes         No

[2088 rows x 28 columns]

In [95]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

# Load the board_games dataset
board_games_data = pd.read_csv("board_games (1).csv")

# Separate the features (X) and the target variable (y)
X = board_games_data.drop(columns=["rating"])
y = board_games_data["rating"]

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Encode categorical variables in the training dataset
X_train_encoded = X_train.copy()
for column in X_train_encoded.columns:
    if X_train_encoded[column].dtype == object:
        X_train_encoded[column] = LabelEncoder().fit_transform(X_train_encoded[column])

# Encode categorical variables in the test dataset
X_test_encoded = X_test.copy()
for column in X_test_encoded.columns:
    if X_test_encoded[column].dtype == object:
        X_test_encoded[column] = LabelEncoder().fit_transform(X_test_encoded[column])

# Fit regression trees on the training dataset
tree6 = DecisionTreeRegressor(random_state=0, ccp_alpha=0.005)
tree6.fit(X_train_encoded, y_train)

# Calculate RMSE for tree6 on the test dataset
y_pred_tree6 = tree6.predict(X_test_encoded)
rmse_tree6 = mean_squared_error(y_test, y_pred_tree6, squared=False)

# Fit regression trees with different cp values
tree7 = DecisionTreeRegressor(random_state=0, ccp_alpha=0.001)
tree7.fit(X_train_encoded, y_train)

tree8 = DecisionTreeRegressor(random_state=0, ccp_alpha=0.0001)
tree8.fit(X_train_encoded, y_train)

tree9 = DecisionTreeRegressor(random_state=0, ccp_alpha=0.1)
tree9.fit(X_train_encoded, y_train)

# Calculate RMSE for tree7, tree8, and tree9 on the test dataset
y_pred_tree7 = tree7.predict(X_test_encoded)
rmse_tree7 = mean_squared_error(y_test, y_pred_tree7, squared=False)

y_pred_tree8 = tree8.predict(X_test_encoded)
rmse_tree8 = mean_squared_error(y_test, y_pred_tree8, squared=False)

y_pred_tree9 = tree9.predict(X_test_encoded)
rmse_tree9 = mean_squared_error(y_test, y_pred_tree9, squared=False)


# Compare RMSE values
lowest_rmse = min(rmse_tree6, rmse_tree7, rmse_tree8, rmse_tree9, rmse_trees)
if lowest_rmse == rmse_tree6:
    answer = "e) tree6"
elif lowest_rmse == rmse_tree7:
    answer = "d) tree7"
elif lowest_rmse == rmse_tree8:
    answer = "a) tree8"
elif lowest_rmse == rmse_tree9:
    answer = "b) tree9"
else:
    answer = "c) tree5"

print("tree that has the lowest RMSE is:",answer)

tree that has the lowest RMSE is: c) tree5

In [61]:
#THE END